---
- name: Ensure that SSHD is installed (RedHat)
  yum:
    name: openssh-server
    state: installed
  when: ansible_distribution == "RedHat"

- name: Ensure that SSHD is installed (SLES)
  zypper:
    name: openssh
    state: installed
  when: ansible_distribution == "SLES"

- name: Deploy SSHD config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: "root"
    group: "root"
    backup: yes
    validate: "sshd -t -f %s" 
  notify: restart sshd

- name: Set Allow Groups
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'AllowGroups {{ allowgroups }}'
    validate: "sshd -t -f %s" 
  changed_when: false

- name: SSH Moduli
  shell: sed -i '/ [1]... \| 2047 /d' /etc/ssh/moduli
  args:
    warn: false
  changed_when: false

- meta: flush_handlers

- name: Check Status of SSHD
  service:
    name: sshd
    state: started
    enabled: yes
