---
- name: Ensure that SSHD is installed (RedHat)
  yum:
    name: openssh-server
    state: installed
  when: ansible_distribution == "RedHat"

- name: Ensure that SSHD is installed (SLES)
  zypper:
    name: openssh
    state: installed
  when: ansible_distribution == "SLES"

- name: Deploy SSHD config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: "root"
    group: "root"
  notify: restart sshd

- name: Check Server Role
  command: "grep -i cds /etc/hostname"
  register: check_role
  failed_when: ( check_role.rc not in [ 0, 1 ] )
  changed_when: false

- name: Set Allow Groups
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'AllowGroups {{ allowgroups }}'
  changed_when: false

- name: Set Allow Users
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'AllowUsers {{ allowusers }}'
  when: check_role.rc == 0
  changed_when: false

- name: SSH Moduli
  shell: sed -i '/ [1]... \| 2047 /d' /etc/ssh/moduli
  args:
    warn: false
  changed_when: false

- meta: flush_handlers

- name: Check Status of SSHD
  service:
    name: sshd
    state: started
    enabled: yes
