--- # Configure ssm-user
- name: Set permissions for ssm-user's home dir
  file:
    path: "/home/ssm-user"
    mode: 0750
    owner: ssm-user
    state: directory

- name: Create .ssh directory
  file:
    path: "/home/ssm-user/.ssh"
    state: directory
    mode: 0700
    owner: ssm-user

- name: Create authorized_keys file
  file:
    path: "/home/ssm-user/.ssh/authorized_keys"
    state: touch
    mode: 0600
    owner: ssm-user

- name: Deploy SSH-keys
  lineinfile:
    path: "/home/ssm-user/authorized_keys"
    line: "{{ pubkeys }}"
