--- # Configure ssm-user
- name: Set permissions for ssm-user's home dir
  file:
    path: "/home/ssm-user"
    mode: 0750
    owner: ssm-user
    state: directory

- name: Ensure group "ssm-user" exists
  group:
    name: ssm-user
    state: present
  when: ansible_distribution == "SLES"

- name: Add existing ssm-user to group ssm-user 
  user:
    name: ssm-user
    groups: ssm-user
    append: yes

- name: Create .ssh directory
  file:
    path: "/home/ssm-user/.ssh"
    state: directory
    mode: 0700
    owner: ssm-user
    group: ssm-user

- name: Create authorized_keys file
  file:
    path: "/home/ssm-user/.ssh/authorized_keys"
    state: touch
    mode: 0600
    owner: ssm-user
    group: ssm-user

- name: Deploy SSH-keys
  copy: 
    content: "{{ pubkeys }}"
    dest: "/home/ssm-user/.ssh/authorized_keys"
