--- # Req 30
- name: Ensure that AUDIT is installed (RedHat)
  yum:
    name: audit
    state: installed
  when: ansible_distribution == "RedHat"

- name: Ensure that AUDIT is installed (SLES)
  zypper:
    name: audit
    state: installed
  when: ansible_distribution == "SLES"

- name: Configure AUDITD
  copy:
    src: "auditd.conf"
    dest: "/etc/audit/auditd.conf"
    mode: 0640
    owner: "root"
    group: "root"

- name: Configure AUDITD rules (RHEL)
  template:
    src: "audit.rules_rhel.j2"
    dest: "/etc/audit/rules.d/audit.rules"
    mode: 0600
    owner: "root"
    group: "root"
  notify: restart auditd
  when: ansible_distribution == "RedHat"

- name: Configure AUDITD rules (SLES)
  template:
    src: "audit.rules_sles.j2"
    dest: "/etc/audit/rules.d/audit.rules"
    mode: 0600
    owner: "root"
    group: "root"
  notify: restart auditd
  when: ansible_distribution == "SLES"

- meta: flush_handlers

#- name: Change parameter for SLES
#  shell: sed -i 's/yum/zypper/' /etc/audit/rules.d/audit.rules
#  args:
#    warn: false
#  when: ansible_distribution == "SLES" 

- name: Check status of AUDITD
  service:
    name: auditd
    state: started
    enabled: yes

- name: Check if GRUB parameter for AUDITD is present
  command: grep audit /etc/default/grub
  register: check_grub
  failed_when: ( check_grub.rc not in [ 0, 1 ] )
  args:
    warn: false
  changed_when: false

#- debug: msg={{ check_grub.rc }}

- name: Add GRUB parameter for AUDITD 
  shell: sed -i '/GRUB_CMDLINE_LINUX=/s/"$/ audit=1"/' /etc/default/grub
  args:
    warn: false
#  changed_when: false
  when: check_grub.rc == 1
  register: grub

- name: Generate new GRUB config
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub.changed
