# Last Steps
- name: Create tsy-info file as last finish step
  copy:
    dest: "/.tsy-info"
    content: |
      TSY Hardening done on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}.

- name: Reboot the instance
  command: "reboot"
