--- # Req 15
- name: Network Hardening
  blockinfile:
    path: /etc/sysctl.d/hardening_ipv4.conf
    block: |
      net.ipv4.ip_forward = 0
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv4.conf.all.secure_redirects = 1
      net.ipv4.conf.default.secure_redirects = 1
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.send_redirects = 0
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.conf.default.log_martians = 1
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      net.ipv4.icmp_ignore_bogus_error_responses = 1
      net.ipv4.conf.all.rp_filter = 1
      net.ipv4.conf.default.rp_filter = 1
      net.ipv4.tcp_syncookies = 1
      net.ipv4.icmp_ratelimit = 100
      net.ipv4.icmp_ratemask = 88089
      net.ipv4.tcp_timestamps = 0
      net.ipv4.conf.all.arp_ignore = 2
      net.ipv4.conf.all.arp_announce = 2
      net.ipv4.conf.all.arp_notify = 0
      net.ipv4.conf.all.arp_accept = 0
    create: yes
    backup: no

- name: Activate IPv4 config
  command: "sysctl --system"
  changed_when: false
