--- # Install additional Packages
- name: Install additional Packages (RedHat)
  yum: name={{ item }} state=present
  loop:
    - git
  when: ansible_distribution == "RedHat"

- name: Install additional Packages (SLES)
  zypper: name={{ item }} state=present
  loop:
    - git
  when: ansible_distribution == "Suse"
