--- # Install additional Packages
- name: Install additional Packages (RedHat)
  yum: name={{ item }} state=present
  loop:
    - git
    - vim
    - acl
  when: ansible_distribution == "RedHat"

- name: Install additional Packages (SLES)
  zypper: name={{ item }} state=present
  loop:
    - git
    - vim
    - acl
  when: ansible_distribution == "SLES"

# Remove unnecessary Packages
- name: Remove unnecessary Packages (RedHat)
  yum: name={{ item }} state=absent
  loop:
    - telnet
  when: ansible_distribution == "RedHat"

- name: Remove unnecessary Packages (SLES)
  zypper: name={{ item }} state=absent
  loop:
    - telnet
  when: ansible_distribution == "SLES"
