--- # Req 45,46,47
- name: Deploy pwquality.conf
  copy:
    src: "pwquality.conf"
    dest: "/etc/security/pwquality.conf"
    mode: 0644
    owner: "root"
    group: "root"

- name: Set PASS_MIN_DAYS parameter in login.defs
  shell: sed -i '/^PASS_MIN_DAYS/s/.*/PASS_MIN_DAYS   1/' /etc/login.defs
  args:
    warn: false
  changed_when: false

- name: Set MIN and MAX encryption rounds parameters in login.defs
  blockinfile:
    path: /etc/login.defs
    block: |
      #
      # SOC Req 10
      SHA_CRYPT_MIN_ROUNDS 640000
      SHA_CRYPT_MAX_ROUNDS 640000
    create: no
    backup: no

- name: Deploy PAM files (RHEL)
  copy:
    src: "pam/system-password-auth"
    dest: "{{ item }}"
    mode: 0644
    owner: "root"
    group: "root"  
  with_items:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth 
  when: ansible_distribution == "RedHat"

- name: Deploy PAM files (SLES)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: 0644
    owner: "root"
    group: "root"
  with_items:
    - { src: 'common-account-pc', dest: '/etc/pam.d/common-account-pc' }
    - { src: 'common-auth-pc', dest: '/etc/pam.d/common-auth-pc' }
    - { src: 'common-password-pc', dest: '/etc/pam.d/common-password-pc' }
    - { src: 'common-session-pc', dest: '/etc/pam.d/common-session-pc' }
  when: ansible_distribution == "SLES"
