--- # Req 45,46,47
- name: Deploy pwquality.conf
  copy:
    src: "pwquality.conf"
    dest: "/etc/security/pwquality.conf"
    mode: 0644
    owner: "root"
    group: "root"

- name: Set PASS_MIN_DAYS parameter in login.defs
  shell: sed -i '/^PASS_MIN_DAYS/s/.*/PASS_MIN_DAYS   1/' /etc/login.defs
  args:
    warn: false
  changed_when: false

- name: Disable motd library
  shell: sed -i '/pam_motd.so/d' /etc/pam.d/sshd
  args:
    warn: false
  changed_when: false

- name: Set MIN and MAX encryption rounds parameters in login.defs
  blockinfile:
    path: /etc/login.defs
    block: |
      #
      # SOC Req 10
      SHA_CRYPT_MIN_ROUNDS 640000
      SHA_CRYPT_MAX_ROUNDS 640000
    create: no
    backup: no

- name: Deploy PAM files (RHEL7)
  copy:
    src: "pam/system-password-auth.rhel7"
    dest: "{{ item }}"
    mode: 0644
    owner: "root"
    group: "root"
  with_items:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'

- name: Deploy PAM files (RHEL8)
  copy:
    src: "pam/system-password-auth.rhel8"
    dest: "{{ item }}"
    mode: 0644
    owner: "root"
    group: "root"  
  with_items:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth 
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '8'

- name: Deploy PAM files (SLES12) 1/2
  copy:
    src: "{{ item }}"
    dest: "/etc/pam.d/"
    mode: 0644
    owner: "root"
    group: "root"
  with_items:
    - pam/common-account-pc
    - pam/common-auth-pc
    - pam/common-session-pc
  when: ansible_distribution == "SLES" and ansible_distribution_major_version == '12'

- name: Deploy PAM files (SLES12) 2/2
  copy:
    src: "pam/common-password-pc-sles12"
    dest: "/etc/pam.d/common-password-pc"
    mode: 0644
    owner: "root"
    group: "root"
  when: ansible_distribution == "SLES" and ansible_distribution_major_version == '12'

- name: Deploy PAM files (SLES15) 1/2
  copy:
    src: "{{ item }}"
    dest: "/etc/pam.d/"
    mode: 0644
    owner: "root"
    group: "root"
  with_items:
    - pam/common-account-pc
    - pam/common-auth-pc
    - pam/common-session-pc
  when: ansible_distribution == "SLES" and ansible_distribution_major_version == '15'

- name: Deploy PAM files (SLES15) 2/2
  copy:
    src: "pam/common-password-pc-sles15"
    dest: "/etc/pam.d/common-password-pc"
    mode: 0644
    owner: "root"
    group: "root"
  when: ansible_distribution == "SLES" and ansible_distribution_major_version == '15'
