--- # 
- name: Copy .rpm file to server
  copy:
     src: rootsh-1.5.3-17.el7.x86_64.rpm
     dest: /tmp/rootsh-1.5.3-17.el7.x86_64.rpm
  when: ansible_distribution == "RedHat"

- name: Install rootsh Package
  yum:
     name: /tmp/rootsh-1.5.3-17.el7.x86_64.rpm
     state: present
     disable_gpg_check: yes
  when: ansible_distribution == "RedHat"

- name: Remove .rpm
  file:
    path: "/tmp/rootsh-1.5.3-17.el7.x86_64.rpm"
    state: absent
  when: ansible_distribution == "RedHat"
