--- # 
- name: Deploy rootsh binary 
  copy:
    src: "rootsh"
    dest: "/usr/bin/rootsh"
    mode: 0755
    owner: "root"
    group: "root"

- name: Create Log dir for rootsh
  file:
    path: "/var/log/rootsh"
    state: directory
    mode: 0700
    owner: root
    group: root

#- name: Set Cronjobs for rootsh logging 
#  blockinfile:
#    path: /etc/crontab
#    block: |
#      # rootsh
#      */1 *  *  *  * root find /var/log/rootsh/ -type f -mmin -1 -name '*.closed' -exec cat {} + >> /var/log/rootsh.log
#      1 0  *  *  *   root find /var/log/rootsh/ -type f -mtime +90 -name '*.closed' -exec rm -f {} +
#      #
#    create: no
#    backup: yes
