# inside .github/workflows/your-action.yml
name: Add File to Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: test
    - run: touch test > all.yml
   
    - uses: zdurham/s3-upload-github-action@master
      name: Upload to S3
      with:
        args: --acl public-read
   env:
    FILE: ./all.yml
    AWS_REGION: 'us-east-1'
    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    S3_KEY: ${{ secrets.S3_KEY }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
